micronaut:
  metrics.binders:
    jvm.enabled: true
    web.enabled: true
    processor.enabled: true
    jdbc.enabled: false
  security:
    enabled: true
    token.jwt:
      enabled: true
      bearer.enabled: true
  caches:
    identity-cache:
      expire-after-write: 10m
    cluster-cache:
      expire-after-write: 1h
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
  executors:
    io:
      type: fixed
      nThreads: 20

endpoints:
  all:
    enabled: true
    path: /endpoints
    sensitive: true

persistence:
  compact:
    threshold: 3d
    schedule.cron: "0 14 2 1/1 * ?"
  read:
    limit: 20000
    max-batch-size: 2000000
    retry-after: 30
    expected-node-count: 3000
    cluster-db-pool-size: 60

datasources:
  postgres:
    jdbc-url: "jdbc:postgresql://${POSTGRE_SERVER}/${POSTGRE_DATABASE}"
    username: "${POSTGRE_USERNAME}"
    password: "${POSTGRE_PASSWORD}"
    driver-class-name: org.postgresql.Driver
    maximum-pool-size: 20

authentication:
  identity:
    delay: 500ms
    attempts: 3

location:
  delay: 500ms
  attempts: 3

registry:
  mark-offline-after: 25m
